<?php

$languages = array(
    '' => '-Default (English)-',
    'ar' => 'Arabic',
    'bg' => 'Bulgarian',
    'ca' => 'Catalan',
    'cs' => 'Czech',
    'da' => 'Danish',
    'de' => 'German',
    'el' => 'Greek',
    'es' => 'Spanish',
    'eu' => 'Basque',
    'fa' => 'Farsi',
    'fi' => 'Finnish',
    'fr' => 'French',
    'he' => 'Hebrew',
    'hu' => 'Hungarian',
    'it' => 'Italian',
    'ja' => 'Japanese',
    'kk' => 'Kazakh',
    'lt' => 'Lietuvių',
    'lv' => 'Latvian',
    'nl' => 'Dutch',
    'no' => 'Norwegian',
    'pl' => 'Polish',
    'ro' => 'Romanian',
    'ru' => 'Russian',
    'si' => 'Sinhala',
    'sk' => 'Slovak',
    'sl' => 'Slovenian',
    'th' => 'Thai',
    'vi' => 'Vietnamese',

);